"""
GUI 리소스 관리
"""

# 아이콘 및 이미지 리소스 (base64 인코딩)
# 실제 프로덕션에서는 별도 리소스 파일 사용 권장

# 애플리케이션 정보
APP_NAME = "Auto Subtitle & Translate"
APP_VERSION = "1.0.0"
APP_AUTHOR = "YJ-20"
APP_DESCRIPTION = "Whisper + LLaMA 기반 자동 자막 생성 및 번역 도구"

# UI 텍스트 (다국어 지원 가능)
UI_TEXT = {
    "ko": {
        "title": "자동 자막 & 번역",
        "subtitle": "Whisper + LLaMA 기반 자동 자막 생성 및 번역",
        "drop_zone": "비디오 파일을 여기에 드래그하세요",
        "supported_formats": "지원 포맷: MP4, AVI, MOV, MKV",
        "browse": "파일 선택",
        "settings": "설정",
        "progress": "진행 상황",
        "start": "처리 시작",
        "cancel": "취소",
        "queue": "대기 중인 파일",
        "model": "Whisper 모델",
        "model_info": "큰 모델일수록 정확도가 높지만 처리 시간이 길어집니다",
        "translation": "번역 설정",
        "enable_translation": "자막 번역 활성화",
        "target_languages": "번역 대상 언어 (다중 선택 가능)",
        "output": "출력 설정",
        "output_folder": "출력 폴더",
        "srt_only": "자막 파일(.srt)만 생성 (비디오 임베딩 안함)",
        "cache": "캐시",
        "cache_info": "처리된 비디오를 캐시에 저장하여 재처리 시간을 단축합니다",
        "clear_cache": "캐시 삭제",
        "processing": "처리 중",
        "completed": "완료",
        "error": "오류",
        "elapsed": "경과 시간",
        "estimated": "예상 남은 시간",
        "log": "처리 로그",
        "completed_files": "완료된 파일"
    },
    "en": {
        "title": "Auto Subtitle & Translate",
        "subtitle": "Automatic subtitle generation and translation with Whisper + LLaMA",
        "drop_zone": "Drag video files here",
        "supported_formats": "Supported formats: MP4, AVI, MOV, MKV",
        "browse": "Browse Files",
        "settings": "Settings",
        "progress": "Progress",
        "start": "Start Processing",
        "cancel": "Cancel",
        "queue": "Files in queue",
        "model": "Whisper Model",
        "model_info": "Larger models are more accurate but take longer to process",
        "translation": "Translation Settings",
        "enable_translation": "Enable subtitle translation",
        "target_languages": "Target languages (multiple selection)",
        "output": "Output Settings",
        "output_folder": "Output folder",
        "srt_only": "Generate subtitle files (.srt) only (no video embedding)",
        "cache": "Cache",
        "cache_info": "Cache processed videos to reduce reprocessing time",
        "clear_cache": "Clear Cache",
        "processing": "Processing",
        "completed": "Completed",
        "error": "Error",
        "elapsed": "Elapsed time",
        "estimated": "Estimated time remaining",
        "log": "Processing log",
        "completed_files": "Completed files"
    }
}

# 언어 코드 매핑
LANGUAGE_NAMES = {
    "ar_AR": "Arabic",
    "cs_CZ": "Czech",
    "de_DE": "German",
    "en_XX": "English",
    "es_XX": "Spanish",
    "et_EE": "Estonian",
    "fi_FI": "Finnish",
    "fr_XX": "French",
    "gu_IN": "Gujarati",
    "hi_IN": "Hindi",
    "it_IT": "Italian",
    "ja_XX": "Japanese",
    "kk_KZ": "Kazakh",
    "ko_KR": "Korean",
    "lt_LT": "Lithuanian",
    "lv_LV": "Latvian",
    "my_MM": "Burmese",
    "ne_NP": "Nepali",
    "nl_XX": "Dutch",
    "ro_RO": "Romanian",
    "ru_RU": "Russian",
    "si_LK": "Sinhala",
    "tr_TR": "Turkish",
    "vi_VN": "Vietnamese",
    "zh_CN": "Chinese",
    "af_ZA": "Afrikaans",
    "az_AZ": "Azerbaijani",
    "bn_IN": "Bengali",
    "fa_IR": "Persian",
    "he_IL": "Hebrew",
    "hr_HR": "Croatian",
    "id_ID": "Indonesian",
    "ka_GE": "Georgian",
    "km_KH": "Khmer",
    "mk_MK": "Macedonian",
    "ml_IN": "Malayalam",
    "mn_MN": "Mongolian",
    "mr_IN": "Marathi",
    "pl_PL": "Polish",
    "ps_AF": "Pashto",
    "pt_XX": "Portuguese",
    "sv_SE": "Swedish",
    "sw_KE": "Swahili",
    "ta_IN": "Tamil",
    "te_IN": "Telugu",
    "th_TH": "Thai",
    "tl_XX": "Tagalog",
    "uk_UA": "Ukrainian",
    "ur_PK": "Urdu",
    "xh_ZA": "Xhosa",
    "gl_ES": "Galician",
    "sl_SI": "Slovene"
}

# 한국어 언어명
LANGUAGE_NAMES_KO = {
    "ar_AR": "아랍어",
    "cs_CZ": "체코어",
    "de_DE": "독일어",
    "en_XX": "영어",
    "es_XX": "스페인어",
    "et_EE": "에스토니아어",
    "fi_FI": "핀란드어",
    "fr_XX": "프랑스어",
    "gu_IN": "구자라트어",
    "hi_IN": "힌디어",
    "it_IT": "이탈리아어",
    "ja_XX": "일본어",
    "kk_KZ": "카자흐어",
    "ko_KR": "한국어",
    "lt_LT": "리투아니아어",
    "lv_LV": "라트비아어",
    "my_MM": "버마어",
    "ne_NP": "네팔어",
    "nl_XX": "네덜란드어",
    "ro_RO": "루마니아어",
    "ru_RU": "러시아어",
    "si_LK": "싱할라어",
    "tr_TR": "터키어",
    "vi_VN": "베트남어",
    "zh_CN": "중국어",
    "af_ZA": "아프리칸스어",
    "az_AZ": "아제르바이잔어",
    "bn_IN": "벵골어",
    "fa_IR": "페르시아어",
    "he_IL": "히브리어",
    "hr_HR": "크로아티아어",
    "id_ID": "인도네시아어",
    "ka_GE": "조지아어",
    "km_KH": "크메르어",
    "mk_MK": "마케도니아어",
    "ml_IN": "말라얄람어",
    "mn_MN": "몽골어",
    "mr_IN": "마라티어",
    "pl_PL": "폴란드어",
    "ps_AF": "파슈토어",
    "pt_XX": "포르투갈어",
    "sv_SE": "스웨덴어",
    "sw_KE": "스와힐리어",
    "ta_IN": "타밀어",
    "te_IN": "텔루구어",
    "th_TH": "태국어",
    "tl_XX": "타갈로그어",
    "uk_UA": "우크라이나어",
    "ur_PK": "우르두어",
    "xh_ZA": "코사어",
    "gl_ES": "갈리시아어",
    "sl_SI": "슬로베니아어"
}